[sailfishos][embedlite] Remove now unused gfxPrefs
See upstream commit: 022c57caf3bca0cc8a64ef44c7d68abc64bfc335

118:45.74 In file included from Unified_cpp_mobile_sailfishos0.cpp:74:
118:45.74 /gecko-dev/mobile/sailfishos/embedprocess/EmbedLiteCompositorProcessParent.cpp:17:10: fatal error: 'gfxPrefs.h' file not found
118:45.74 #include "gfxPrefs.h"
118:45.74          ^~~~~~~~~~~~