[sailfishos][embedlite] nsPIDOMWindowInner::Freeze, nsPIDOMWindowInner::Thaw were removed. RECHECK
See upstream commit: c70cb82b91e531c643d83b4da3a3cd39c80a8e34

7:21.94 In file included from Unified_cpp_mobile_sailfishos0.cpp:137:
7:21.94 /gecko-dev/mobile/sailfishos/embedshared/EmbedLiteViewChild.cpp:659:14: error: no member named 'Freeze' in 'nsPIDOMWindowInner'
7:21.94     pwindow->Freeze();
7:21.94     ~~~~~~~  ^
7:21.95 /gecko-dev/mobile/sailfishos/embedshared/EmbedLiteViewChild.cpp:672:14: error: no member named 'Thaw' in 'nsPIDOMWindowInner'
7:21.95     pwindow->Thaw();
7:21.95     ~~~~~~~  ^